CREATE SCHEMA IF NOT EXISTS app_users;

CREATE TABLE IF NOT EXISTS app_users.users (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);